
export const FAVORITE_LIST_REQUEST = 'FAVORITE_LIST_REQUEST'
export const FAVORITE_LIST_SUCCESS = 'FAVORITE_LIST_SUCCESS'
export const FAVORITE_LIST_FAILURE = 'FAVORITE_LIST_FAILURE'
export const FAVORITE_ITEM_ADD_REQUEST = 'FAVORITE_ITEM_ADD_REQUEST'
export const FAVORITE_ITEM_ADD_SUCCESS = 'FAVORITE_ITEM_ADD_SUCCESS'
export const FAVORITE_ITEM_ADD_FAILURE = 'FAVORITE_ITEM_ADD_FAILURE'
export const FAVORITE_ITEM_REMOVE_REQUEST = 'FAVORITE_ITEM_REMOVE_REQUEST'
export const FAVORITE_ITEM_REMOVE_SUCCESS = 'FAVORITE_ITEM_REMOVE_SUCCESS'
export const FAVORITE_ITEM_REMOVE_FAILURE = 'FAVORITE_ITEM_REMOVE_FAILURE'
export const FAVORITE_LIST_CLEAN = "FAVORITE_LIST_CLEAN"